<?php
/**
 * TL_ROOT/system/modules/banner/languages/cs/default.php 
 * 
 * Contao extension: banner 2.4.4 stable 
 * Czech translation file 
 * 
 * Copyright : &copy; 2007..2013 Glen Langer 
 * License   : GNU GPL V2 
 * Author    : Glen Langer (BugBuster), http://www.contao.glen-langer.de 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['id'] = "ID";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['picture'] = "Banner";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['name'] = "Jméno";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['URL'] = "Cílové URL";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['views'] = "Zobrazení";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['clicks'] = "Kliknutí";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['NoURL'] = "Není URL";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['Prio'] = "Priorita";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['active'] = "Aktivní";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['pub_yes'] = "ano";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['pub_no'] = "ne";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['max_yes'] = "(Maximum)";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['modname'] = "Banner Module";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['export'] = "Export";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['export_button_title'] = "Tlačítko otevře nové okno.";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['export_headline'] = "Kategorie,ID,Jméno,Adresa URL,Obrázek,Priorita,Zobrazit od,Zobrazit do,Publikováno,Zobrazení,Kliknutí";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['zero_text'] = "Resetovat počítadlo, statistika bude vynulována.";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['zero_confirm'] = "Opravdu chcete vynulovat statistiky k banneru (zobrazení a kliknutí)?";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['cat_zero'] = "Statistika";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['cat_zero_button'] = "Reset všech bannerů";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['cat_zero_text'] = "Statistiky všech banneru v této kategorii budou vynulovány.";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['cat_zero_confirm'] = "Opravdu chcete vynulovat statistiky všech banneru v této kategorii?";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['kat'] = "Kategorie";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['allkat'] = "Všechny kategorie";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['read_error'] = "Banner nebyl nalezen nebo chyba čtení!";
$GLOBALS['TL_LANG']['MSC']['tl_banner_stat']['select'] = "Prosím, vyberte";
 
?>
