<?php
/**
 * TL_ROOT/system/modules/banner/languages/cs/modules.php 
 * 
 * Contao extension: banner 2.4.4 stable 
 * Czech translation file 
 * 
 * Copyright : &copy; 2007..2013 Glen Langer 
 * License   : GNU GPL V2 
 * Author    : Glen Langer (BugBuster), http://www.contao.glen-langer.de 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['banner']['0'] = "Banner";
$GLOBALS['TL_LANG']['MOD']['banner']['1'] = "Modul pro správu bannerů s jednoduchou formou statistik.";
$GLOBALS['TL_LANG']['MOD']['bannerstat']['0'] = "Banner Statistika";
$GLOBALS['TL_LANG']['MOD']['bannerstat']['1'] = "Statistiky pro modul správy bannerů.";
$GLOBALS['TL_LANG']['FMD']['banner']['0'] = "Banner";
$GLOBALS['TL_LANG']['FMD']['banner']['1'] = "Zobrazit banner";
 
?>
