<?php
/**
 * TL_ROOT/system/modules/banner/languages/cs/tl_module.php 
 * 
 * Contao extension: banner 2.4.4 stable 
 * Czech translation file 
 * 
 * Copyright : &copy; 2007..2013 Glen Langer 
 * License   : GNU GPL V2 
 * Author    : Glen Langer (BugBuster), http://www.contao.glen-langer.de 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['banner_hideempty']['0'] = "Skrýt, když je prázdný";
$GLOBALS['TL_LANG']['tl_module']['banner_hideempty']['1'] = "Skrýt modul (frontend), kdy nejsou nalezeny žádné aktivní bannery.";
$GLOBALS['TL_LANG']['tl_module']['banner_firstview']['0'] = "První banner pro nového návštěvníka";
$GLOBALS['TL_LANG']['tl_module']['banner_firstview']['1'] = "U každého nového návštěvníka, nejprve se zobrazí první banner v kategorii. Výběr se pak vrátí k náhodné režimu.";
$GLOBALS['TL_LANG']['tl_module']['banner_categories']['0'] = "Banner kategorie";
$GLOBALS['TL_LANG']['tl_module']['banner_categories']['1'] = "Prosím, vyberte kategorii banneru.";
$GLOBALS['TL_LANG']['tl_module']['banner_template']['0'] = "Banner šablony";
$GLOBALS['TL_LANG']['tl_module']['banner_template']['1'] = "Prosím, vyberte banner šablony. Začít se soubory šablon<em>mod_banner_list_</em>.";
$GLOBALS['TL_LANG']['tl_module']['banner_useragent']['0'] = "Žádné počítání pro tento HTTP_USER_AGENT částečný identifikátor";
$GLOBALS['TL_LANG']['tl_module']['banner_useragent']['1'] = "Here you can specify a partial identifier, it will be no counting. These HTTP_USER_AGENT partial identifier of the browser must be changed.<br />See Wiki.";
 
?>
