<?php
/**
 * TL_ROOT/system/modules/banner/languages/fa/explain.php 
 * 
 * Contao extension: banner 2.4.3 stable 
 * Persian translation file 
 * 
 * Copyright : &copy; 2007..2012 Glen Langer 
 * License   : GNU GPL V2 
 * Author    : Glen Langer (BugBuster), http://www.contao.glen-langer.de 
 * Translator: Hamid Abbaszadeh (respinar), http://www.contao.ir/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['XPL']['banner_help']['0']['0'] = "نام بنر";
$GLOBALS['TL_LANG']['XPL']['banner_help']['1']['0'] = "نشانی وب بنر";
$GLOBALS['TL_LANG']['XPL']['banner_help']['2']['0'] = "توزین بنر";
$GLOBALS['TL_LANG']['XPL']['banner_help']['3']['0'] = "تصویر بنر";
$GLOBALS['TL_LANG']['XPL']['banner_help']['4']['0'] = "نظر بنر";
$GLOBALS['TL_LANG']['XPL']['banner_help']['5']['0'] = "مشاهده از تاریخ و ساعت";
$GLOBALS['TL_LANG']['XPL']['banner_help']['6']['0'] = "مشاهده تا تاریخ و ساعت";
$GLOBALS['TL_LANG']['XPL']['banner_help']['7']['0'] = "محدود کردن تعداد بازدید";
$GLOBALS['TL_LANG']['XPL']['banner_help']['8']['0'] = "محدود کردن تعداد کلیک ها";
$GLOBALS['TL_LANG']['XPL']['banner_help']['9']['0'] = "شناسه جزئی HTTP_USER_AGENT";
 
?>
